In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
# for work pc
data_hh = pd.read_csv('D:\Course_SF_DS\PROJECT-1. Анализ резюме из HeadHunter\data\dst-3.0_16_1_hh_database.csv', sep=';')

# for home mac
#data_hh = pd.read_csv('/Users/sergejrybackov/Documents/DataSaintisst/dst-3.0_16_1_hh_database.csv', sep=';')

In [3]:
data_hh.head()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

In [21]:

def experience(data):
    if type(data) == float:
        return np.nan
    else:
        
        sp_data = data.split(' ')
        sp_data = sp_data[:6]

        # Создадим вспомогательные списки с возможным отображением лет и месяцев
        year_list = ['год', 'года', 'лет']
        month_list = ['месяц', 'месяца', 'месяцев']

        res_year = 0
        res_month = 0

        for i in range(len(sp_data)):
            if sp_data[i] in year_list:
                res_year = sp_data[i-1]
            if sp_data[i] in month_list:
                res_month = sp_data[i-1]
            
        result = int(res_year) * 12 + int(res_month)

        if result == 0:
            return np.nan
        else:
            return result

data_hh['Опыт работы (месяц)'] = data_hh['Опыт работы'].apply(experience)
data_hh['Опыт работы (месяц)'].median()

100.0